-- Enable necessary extensions
create extension if not exists "uuid-ossp";

-- Table: users (Public profile linked to auth.users)
create table if not exists public.users (
  id uuid references auth.users on delete cascade primary key,
  nama text not null,
  email text not null unique,
  peran text not null default 'admin' check (peran in ('super-admin', 'admin', 'guru')),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Table: guru
create table if not exists public.guru (
  id bigint generated by default as identity primary key,
  nama text not null,
  kategori text default 'pendidik' check (kategori in ('pendidik', 'tenaga_kependidikan')),
  jenis_kelamin text,
  jabatan text,
  mata_pelajaran text,
  urutan smallint default 0,
  aktif boolean default true,
  image_url text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Add guru_id to users now that guru table exists
alter table public.users add column if not exists guru_id bigint references public.guru(id) on delete restrict unique;

-- Ensure users_peran_check constraint supports ('super-admin', 'admin', 'guru')
alter table public.users drop constraint if exists users_peran_check;
alter table public.users add constraint users_peran_check check (peran in ('super-admin', 'admin', 'guru'));

-- Table: berita
create table if not exists public.berita (
  id bigint generated by default as identity primary key,
  judul text not null,
  slug text not null unique,
  ringkasan text,
  isi text not null,
  status text default 'draft' check (status in ('draft', 'terbit')),
  diterbitkan_pada timestamptz,
  penulis_id uuid references public.users(id) on delete set null,
  image_url text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Table: struktur_organisasi
create table if not exists public.struktur_organisasi (
  id bigint generated by default as identity primary key,
  label text not null,
  guru_id bigint references public.guru(id) on delete set null,
  atasan_id bigint references public.struktur_organisasi(id) on delete cascade,
  tipe text default 'orang' check (tipe in ('orang', 'kelompok', 'penasihat')),
  nama_luar text,
  baris smallint default 1,
  urutan smallint default 0,
  image_url text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Table: ekstrakurikuler
create table if not exists public.ekstrakurikuler (
  id bigint generated by default as identity primary key,
  nama text not null,
  slug text not null unique,
  deskripsi text,
  pembina text,
  jadwal text,
  urutan smallint default 0,
  image_url text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Table: album
create table if not exists public.album (
  id bigint generated by default as identity primary key,
  judul text not null,
  slug text not null unique,
  deskripsi text,
  urutan smallint default 0,
  image_url text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Table: konten_halaman
create table if not exists public.konten_halaman (
  id bigint generated by default as identity primary key,
  kunci text not null unique,
  judul text not null,
  isi text,
  terbit boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Table: pengaturan_situs
create table if not exists public.pengaturan_situs (
  id bigint generated by default as identity primary key,
  nama_sekolah text default 'SMA Ahlul Irfan Bangsalsari',
  nama_yayasan text,
  semboyan text,
  alamat text,
  telepon text,
  whatsapp text,
  email text,
  peta_lat numeric(10, 7),
  peta_lng numeric(10, 7),
  npsn text,
  akreditasi text,
  instagram text,
  facebook text,
  youtube text,
  fakta_terverifikasi boolean default false,
  logo_url text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Phase 2 Tables (Absensi)
create table if not exists public.tahun_ajaran (
  id bigint generated by default as identity primary key,
  nama varchar(20) not null,
  semester varchar(10) not null check (semester in ('ganjil', 'genap')),
  mulai_pada date not null,
  selesai_pada date not null check (selesai_pada >= mulai_pada),
  aktif boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (nama, semester)
);

-- Ensure only one active academic year at a time
create unique index if not exists only_one_active_tahun_ajaran
  on public.tahun_ajaran (aktif)
  where aktif = true;

create table if not exists public.kelas (
  id bigint generated by default as identity primary key,
  tahun_ajaran_id bigint not null references public.tahun_ajaran(id) on delete restrict,
  nama varchar(50) not null,
  tingkat smallint not null check (tingkat in (10, 11, 12)),
  wali_kelas_id bigint references public.guru(id) on delete restrict,
  aktif boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tahun_ajaran_id, nama)
);

create index if not exists idx_kelas_tahun_ajaran on public.kelas (tahun_ajaran_id);
create index if not exists idx_kelas_wali_kelas on public.kelas (wali_kelas_id);

create table if not exists public.siswa (
  id bigint generated by default as identity primary key,
  kode_siswa varchar(30) not null unique,
  nama varchar(150) not null,
  jenis_kelamin varchar(1) check (jenis_kelamin in ('L', 'P')),
  aktif boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_siswa_kode on public.siswa (kode_siswa);

create table if not exists public.anggota_kelas (
  id bigint generated by default as identity primary key,
  kelas_id bigint not null references public.kelas(id) on delete restrict,
  siswa_id bigint not null references public.siswa(id) on delete restrict,
  mulai_pada date not null,
  selesai_pada date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_anggota_kelas_kelas_dates on public.anggota_kelas (kelas_id, mulai_pada, selesai_pada);
create index if not exists idx_anggota_kelas_siswa_dates on public.anggota_kelas (siswa_id, mulai_pada, selesai_pada);

create table if not exists public.presensi (
  id bigint generated by default as identity primary key,
  kelas_id bigint not null references public.kelas(id) on delete restrict,
  tanggal date not null,
  status varchar(10) not null default 'draf' check (status in ('draf', 'selesai')),
  dicatat_oleh uuid not null references public.users(id) on delete restrict,
  versi int not null default 1,
  selesai_pada timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (kelas_id, tanggal)
);

create index if not exists idx_presensi_kelas_tanggal on public.presensi (kelas_id, tanggal);

create table if not exists public.kehadiran_siswa (
  id bigint generated by default as identity primary key,
  presensi_id bigint not null references public.presensi(id) on delete cascade,
  siswa_id bigint not null references public.siswa(id) on delete restrict,
  status varchar(20) not null default 'belum_diisi' check (status in ('belum_diisi', 'hadir', 'sakit', 'izin', 'alpa', 'terlambat')),
  catatan varchar(255),
  diubah_oleh uuid not null references public.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (presensi_id, siswa_id)
);

create index if not exists idx_kehadiran_siswa_presensi on public.kehadiran_siswa (presensi_id);
create index if not exists idx_kehadiran_siswa_siswa on public.kehadiran_siswa (siswa_id);

create table if not exists public.riwayat_presensi (
  id bigint generated by default as identity primary key,
  presensi_id bigint not null references public.presensi(id) on delete restrict,
  siswa_id bigint references public.siswa(id) on delete restrict,
  user_id uuid not null references public.users(id) on delete restrict,
  aksi varchar(20) not null check (aksi in ('buat_draf', 'simpan_draf', 'selesaikan', 'ubah_status')),
  status_sebelum varchar(20),
  status_sesudah varchar(20),
  catatan_sebelum varchar(255),
  catatan_sesudah varchar(255),
  alasan varchar(255),
  created_at timestamptz not null default now()
);

create index if not exists idx_riwayat_presensi_presensi on public.riwayat_presensi (presensi_id);

-- Enable Row Level Security (RLS) on all tables
alter table public.users enable row level security;
alter table public.guru enable row level security;
alter table public.berita enable row level security;
alter table public.struktur_organisasi enable row level security;
alter table public.ekstrakurikuler enable row level security;
alter table public.album enable row level security;
alter table public.konten_halaman enable row level security;
alter table public.pengaturan_situs enable row level security;
alter table public.tahun_ajaran enable row level security;
alter table public.kelas enable row level security;
alter table public.siswa enable row level security;
alter table public.anggota_kelas enable row level security;
alter table public.presensi enable row level security;
alter table public.kehadiran_siswa enable row level security;
alter table public.riwayat_presensi enable row level security;

-- ==============================================================================
-- HELPER FUNCTIONS (Security Definer & Stable)
-- ==============================================================================

-- Check if current user is admin or super-admin
create or replace function public.is_admin()
returns boolean as $$
  select exists (
    select 1 from public.users
    where id = auth.uid()
      and peran in ('admin', 'super-admin')
  );
$$ language sql security definer;

-- Get current user's linked guru_id
create or replace function public.current_guru_id()
returns bigint as $$
  select guru_id from public.users
  where id = auth.uid();
$$ language sql security definer;

-- Check if a given date is today in WIB (Asia/Jakarta)
create or replace function public.is_today_wib(p_tanggal date)
returns boolean as $$
  select p_tanggal = (timezone('Asia/Jakarta', now())::date);
$$ language sql stable;

-- Get current date in WIB (Asia/Jakarta)
create or replace function public.today_wib()
returns date as $$
  select timezone('Asia/Jakarta', now())::date;
$$ language sql stable;

-- ==============================================================================
-- RLS POLICIES
-- ==============================================================================

-- Public read policies for profile website
drop policy if exists "Allow public read access to active guru" on public.guru;
create policy "Allow public read access to active guru" on public.guru for select using (aktif = true);

drop policy if exists "Allow public read access to published berita" on public.berita;
create policy "Allow public read access to published berita" on public.berita for select using (status = 'terbit');

drop policy if exists "Allow public read access to struktur_organisasi" on public.struktur_organisasi;
create policy "Allow public read access to struktur_organisasi" on public.struktur_organisasi for select using (true);

drop policy if exists "Allow public read access to ekstrakurikuler" on public.ekstrakurikuler;
create policy "Allow public read access to ekstrakurikuler" on public.ekstrakurikuler for select using (true);

drop policy if exists "Allow public read access to album" on public.album;
create policy "Allow public read access to album" on public.album for select using (true);

drop policy if exists "Allow public read access to published konten_halaman" on public.konten_halaman;
create policy "Allow public read access to published konten_halaman" on public.konten_halaman for select using (terbit = true);

drop policy if exists "Allow public read access to pengaturan_situs" on public.pengaturan_situs;
create policy "Allow public read access to pengaturan_situs" on public.pengaturan_situs for select using (true);

-- Admin full management policies
drop policy if exists "Admins can do everything on guru" on public.guru;
create policy "Admins can do everything on guru" on public.guru to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Admins can do everything on berita" on public.berita;
create policy "Admins can do everything on berita" on public.berita to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Admins can do everything on struktur_organisasi" on public.struktur_organisasi;
create policy "Admins can do everything on struktur_organisasi" on public.struktur_organisasi to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Admins can do everything on ekstrakurikuler" on public.ekstrakurikuler;
create policy "Admins can do everything on ekstrakurikuler" on public.ekstrakurikuler to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Admins can do everything on album" on public.album;
create policy "Admins can do everything on album" on public.album to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Admins can do everything on konten_halaman" on public.konten_halaman;
create policy "Admins can do everything on konten_halaman" on public.konten_halaman to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Admins can do everything on pengaturan_situs" on public.pengaturan_situs;
create policy "Admins can do everything on pengaturan_situs" on public.pengaturan_situs to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Admins can do everything on users" on public.users;
create policy "Admins can do everything on users" on public.users to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Users can read own profile" on public.users;
create policy "Users can read own profile" on public.users for select to authenticated using (auth.uid() = id);

-- Absensi: tahun_ajaran policies
drop policy if exists "Admins can do everything on tahun_ajaran" on public.tahun_ajaran;
create policy "Admins can do everything on tahun_ajaran" on public.tahun_ajaran
  to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Authenticated users can view tahun_ajaran" on public.tahun_ajaran;
create policy "Authenticated users can view tahun_ajaran" on public.tahun_ajaran
  for select to authenticated using (true);

-- Absensi: kelas policies
drop policy if exists "Admins can do everything on kelas" on public.kelas;
create policy "Admins can do everything on kelas" on public.kelas
  to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Guru can view assigned kelas" on public.kelas;
create policy "Guru can view assigned kelas" on public.kelas
  for select to authenticated using (
    public.is_admin() or (wali_kelas_id is not null and wali_kelas_id = public.current_guru_id())
  );

-- Absensi: siswa policies
drop policy if exists "Admins can do everything on siswa" on public.siswa;
create policy "Admins can do everything on siswa" on public.siswa
  to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Guru can view siswa in assigned kelas" on public.siswa;
create policy "Guru can view siswa in assigned kelas" on public.siswa
  for select to authenticated using (
    public.is_admin() or exists (
      select 1 from public.anggota_kelas ak
      join public.kelas k on k.id = ak.kelas_id
      where ak.siswa_id = public.siswa.id
        and k.wali_kelas_id = public.current_guru_id()
    )
  );

-- Absensi: anggota_kelas policies
drop policy if exists "Admins can do everything on anggota_kelas" on public.anggota_kelas;
create policy "Admins can do everything on anggota_kelas" on public.anggota_kelas
  to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Guru can view anggota_kelas in assigned kelas" on public.anggota_kelas;
create policy "Guru can view anggota_kelas in assigned kelas" on public.anggota_kelas
  for select to authenticated using (
    public.is_admin() or exists (
      select 1 from public.kelas k
      where k.id = public.anggota_kelas.kelas_id
        and k.wali_kelas_id = public.current_guru_id()
    )
  );

-- Absensi: presensi policies
drop policy if exists "Admins can manage all presensi" on public.presensi;
create policy "Admins can manage all presensi" on public.presensi
  to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Guru can view presensi of assigned kelas" on public.presensi;
create policy "Guru can view presensi of assigned kelas" on public.presensi
  for select to authenticated using (
    public.is_admin() or exists (
      select 1 from public.kelas k
      where k.id = public.presensi.kelas_id
        and k.wali_kelas_id = public.current_guru_id()
    )
  );

drop policy if exists "Guru can insert presensi for today in assigned kelas" on public.presensi;
create policy "Guru can insert presensi for today in assigned kelas" on public.presensi
  for insert to authenticated with check (
    public.is_admin() or (
      public.is_today_wib(tanggal)
      and exists (
        select 1 from public.kelas k
        where k.id = public.presensi.kelas_id
          and k.wali_kelas_id = public.current_guru_id()
      )
    )
  );

drop policy if exists "Guru can update presensi for today in assigned kelas" on public.presensi;
create policy "Guru can update presensi for today in assigned kelas" on public.presensi
  for update to authenticated using (
    public.is_admin() or (
      public.is_today_wib(tanggal)
      and exists (
        select 1 from public.kelas k
        where k.id = public.presensi.kelas_id
          and k.wali_kelas_id = public.current_guru_id()
      )
    )
  ) with check (
    public.is_admin() or (
      public.is_today_wib(tanggal)
      and exists (
        select 1 from public.kelas k
        where k.id = public.presensi.kelas_id
          and k.wali_kelas_id = public.current_guru_id()
      )
    )
  );

drop policy if exists "No one can delete presensi" on public.presensi;
create policy "No one can delete presensi" on public.presensi
  for delete to authenticated using (false);

-- Absensi: kehadiran_siswa policies
drop policy if exists "Admins can do everything on kehadiran_siswa" on public.kehadiran_siswa;
create policy "Admins can do everything on kehadiran_siswa" on public.kehadiran_siswa
  to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Users can view kehadiran_siswa for allowed presensi" on public.kehadiran_siswa;
create policy "Users can view kehadiran_siswa for allowed presensi" on public.kehadiran_siswa
  for select to authenticated using (
    public.is_admin() or exists (
      select 1 from public.presensi p
      join public.kelas k on k.id = p.kelas_id
      where p.id = public.kehadiran_siswa.presensi_id
        and k.wali_kelas_id = public.current_guru_id()
    )
  );

drop policy if exists "Users can insert kehadiran_siswa for allowed presensi" on public.kehadiran_siswa;
create policy "Users can insert kehadiran_siswa for allowed presensi" on public.kehadiran_siswa
  for insert to authenticated with check (
    public.is_admin() or exists (
      select 1 from public.presensi p
      join public.kelas k on k.id = p.kelas_id
      where p.id = public.kehadiran_siswa.presensi_id
        and k.wali_kelas_id = public.current_guru_id()
        and public.is_today_wib(p.tanggal)
    )
  );

drop policy if exists "Users can update kehadiran_siswa for allowed presensi" on public.kehadiran_siswa;
create policy "Users can update kehadiran_siswa for allowed presensi" on public.kehadiran_siswa
  for update to authenticated using (
    public.is_admin() or exists (
      select 1 from public.presensi p
      join public.kelas k on k.id = p.kelas_id
      where p.id = public.kehadiran_siswa.presensi_id
        and k.wali_kelas_id = public.current_guru_id()
        and public.is_today_wib(p.tanggal)
    )
  ) with check (
    public.is_admin() or exists (
      select 1 from public.presensi p
      join public.kelas k on k.id = p.kelas_id
      where p.id = public.kehadiran_siswa.presensi_id
        and k.wali_kelas_id = public.current_guru_id()
        and public.is_today_wib(p.tanggal)
    )
  );

drop policy if exists "No one can delete kehadiran_siswa" on public.kehadiran_siswa;
create policy "No one can delete kehadiran_siswa" on public.kehadiran_siswa
  for delete to authenticated using (false);

-- Absensi: riwayat_presensi policies (Append-Only Audit Log)
drop policy if exists "Admins can do everything on riwayat_presensi" on public.riwayat_presensi;
create policy "Admins can do everything on riwayat_presensi" on public.riwayat_presensi
  to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Users can view riwayat_presensi for allowed presensi" on public.riwayat_presensi;
create policy "Users can view riwayat_presensi for allowed presensi" on public.riwayat_presensi
  for select to authenticated using (
    public.is_admin() or exists (
      select 1 from public.presensi p
      join public.kelas k on k.id = p.kelas_id
      where p.id = public.riwayat_presensi.presensi_id
        and k.wali_kelas_id = public.current_guru_id()
    )
  );

drop policy if exists "Users can insert riwayat_presensi for allowed presensi" on public.riwayat_presensi;
create policy "Users can insert riwayat_presensi for allowed presensi" on public.riwayat_presensi
  for insert to authenticated with check (
    public.is_admin() or exists (
      select 1 from public.presensi p
      join public.kelas k on k.id = p.kelas_id
      where p.id = public.riwayat_presensi.presensi_id
        and k.wali_kelas_id = public.current_guru_id()
    )
  );

drop policy if exists "No one can update riwayat_presensi" on public.riwayat_presensi;
create policy "No one can update riwayat_presensi" on public.riwayat_presensi
  for update to authenticated using (false);

drop policy if exists "No one can delete riwayat_presensi" on public.riwayat_presensi;
create policy "No one can delete riwayat_presensi" on public.riwayat_presensi
  for delete to authenticated using (false);

-- ==============================================================================
-- STORED PROCEDURE / RPC: simpan_presensi
-- ==============================================================================
-- Atomic transaction to save attendance session, validate optimistic locking version,
-- upsert student presence records, and record append-only audit trail.

create or replace function public.simpan_presensi(
  p_kelas_id bigint,
  p_tanggal date,
  p_versi int,
  p_baris jsonb,
  p_selesaikan boolean default false,
  p_alasan text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid;
  v_is_admin boolean;
  v_guru_id bigint;
  v_wali_kelas_id bigint;
  v_presensi public.presensi%rowtype;
  v_existing_kehadiran public.kehadiran_siswa%rowtype;
  v_elem jsonb;
  v_siswa_id bigint;
  v_status varchar(20);
  v_catatan varchar(255);
  v_today date;
  v_is_new_session boolean := false;
  v_updated_rows int := 0;
begin
  -- 1. Check authentication
  v_user_id := auth.uid();
  if v_user_id is null then
    raise exception 'UNAUTHORIZED: Pengguna tidak terautentikasi.' using errcode = '42501';
  end if;

  v_today := (timezone('Asia/Jakarta', now())::date);

  -- 2. Validate date (cannot be in the future)
  if p_tanggal > v_today then
    raise exception 'VALIDASI_GAGAL: Tanggal presensi tidak boleh di masa depan.' using errcode = '22023';
  end if;

  -- 3. Authorization check
  v_is_admin := exists (
    select 1 from public.users where id = v_user_id and peran in ('admin', 'super-admin')
  );

  if not v_is_admin then
    -- Must be a guru assigned as wali_kelas
    select guru_id into v_guru_id from public.users where id = v_user_id;
    if v_guru_id is null then
      raise exception 'FORBIDDEN: Akun Anda belum terhubung dengan data guru.' using errcode = '42501';
    end if;

    select wali_kelas_id into v_wali_kelas_id from public.kelas where id = p_kelas_id;
    if v_wali_kelas_id is null or v_wali_kelas_id != v_guru_id then
      raise exception 'FORBIDDEN: Anda bukan wali kelas dari kelas ini.' using errcode = '42501';
    end if;

    -- Guru can only edit today
    if p_tanggal != v_today then
      raise exception 'FORBIDDEN: Guru hanya dapat mengisi atau mengubah presensi untuk hari ini.' using errcode = '42501';
    end if;
  else
    -- Admin editing past date requires reason of at least 10 chars
    if p_tanggal < v_today then
      if p_alasan is null or length(trim(p_alasan)) < 10 then
        raise exception 'VALIDASI_GAGAL: Alasan koreksi tanggal lampau wajib diisi minimal 10 karakter.' using errcode = '22023';
      end if;
    end if;
  end if;

  -- 4. Finalization rule: if finalizing, ensure no status is 'belum_diisi'
  if p_selesaikan then
    for v_elem in select * from jsonb_array_elements(p_baris)
    loop
      v_status := v_elem->>'status';
      if v_status is null or v_status = 'belum_diisi' then
        raise exception 'VALIDASI_GAGAL: Semua siswa harus memiliki status kehadiran (tidak boleh belum diisi) untuk menyelesaikan absensi.' using errcode = '22023';
      end if;
    end loop;
  end if;

  -- 5. Lock and retrieve or insert presensi session
  select * into v_presensi
  from public.presensi
  where kelas_id = p_kelas_id and tanggal = p_tanggal
  for update;

  if not found then
    v_is_new_session := true;
    insert into public.presensi (
      kelas_id,
      tanggal,
      status,
      dicatat_oleh,
      versi,
      selesai_pada
    ) values (
      p_kelas_id,
      p_tanggal,
      case when p_selesaikan then 'selesai' else 'draf' end,
      v_user_id,
      1,
      case when p_selesaikan then now() else null end
    )
    returning * into v_presensi;

    -- Log audit for session creation
    insert into public.riwayat_presensi (
      presensi_id,
      siswa_id,
      user_id,
      aksi,
      status_sebelum,
      status_sesudah,
      alasan
    ) values (
      v_presensi.id,
      null,
      v_user_id,
      case when p_selesaikan then 'selesai' else 'buat_draf' end,
      null,
      case when p_selesaikan then 'selesai' else 'draf' end,
      p_alasan
    );
  else
    -- Version check for optimistic concurrency control
    if v_presensi.versi != p_versi then
      raise exception 'KONFLIK_VERSI: Data telah diubah pengguna lain (versi database: %, versi dikirim: %). Muat ulang sebelum menyimpan.'
        , v_presensi.versi, p_versi
        using errcode = 'P0001';
    end if;

    -- Update session
    update public.presensi
    set
      status = case when p_selesaikan then 'selesai' else status end,
      versi = v_presensi.versi + 1,
      selesai_pada = case
        when p_selesaikan and selesai_pada is null then now()
        else selesai_pada
      end,
      updated_at = now()
    where id = v_presensi.id
    returning * into v_presensi;

    -- If status changed to selesai
    if p_selesaikan and v_presensi.status = 'selesai' then
      insert into public.riwayat_presensi (
        presensi_id,
        siswa_id,
        user_id,
        aksi,
        status_sebelum,
        status_sesudah,
        alasan
      ) values (
        v_presensi.id,
        null,
        v_user_id,
        'selesaikan',
        'draf',
        'selesai',
        p_alasan
      );
    end if;
  end if;

  -- 6. Upsert kehadiran_siswa & record audit log for each student
  for v_elem in select * from jsonb_array_elements(p_baris)
  loop
    v_siswa_id := (v_elem->>'siswa_id')::bigint;
    v_status := coalesce(v_elem->>'status', 'belum_diisi');
    v_catatan := v_elem->>'catatan';

    -- Validate status value
    if v_status not in ('belum_diisi', 'hadir', 'sakit', 'izin', 'alpa', 'terlambat') then
      raise exception 'VALIDASI_GAGAL: Status kehadiran "%" tidak valid.', v_status using errcode = '22023';
    end if;

    select * into v_existing_kehadiran
    from public.kehadiran_siswa
    where presensi_id = v_presensi.id and siswa_id = v_siswa_id
    for update;

    if not found then
      -- Insert new attendance record
      insert into public.kehadiran_siswa (
        presensi_id,
        siswa_id,
        status,
        catatan,
        diubah_oleh
      ) values (
        v_presensi.id,
        v_siswa_id,
        v_status,
        v_catatan,
        v_user_id
      );

      -- Record audit log
      insert into public.riwayat_presensi (
        presensi_id,
        siswa_id,
        user_id,
        aksi,
        status_sebelum,
        status_sesudah,
        catatan_sebelum,
        catatan_sesudah,
        alasan
      ) values (
        v_presensi.id,
        v_siswa_id,
        v_user_id,
        case when v_is_new_session then 'buat_draf' else 'ubah_status' end,
        null,
        v_status,
        null,
        v_catatan,
        p_alasan
      );
    else
      -- Check if status or notes changed
      if v_existing_kehadiran.status is distinct from v_status
         or v_existing_kehadiran.catatan is distinct from v_catatan then

        insert into public.riwayat_presensi (
          presensi_id,
          siswa_id,
          user_id,
          aksi,
          status_sebelum,
          status_sesudah,
          catatan_sebelum,
          catatan_sesudah,
          alasan
        ) values (
          v_presensi.id,
          v_siswa_id,
          v_user_id,
          'ubah_status',
          v_existing_kehadiran.status,
          v_status,
          v_existing_kehadiran.catatan,
          v_catatan,
          p_alasan
        );

        update public.kehadiran_siswa
        set
          status = v_status,
          catatan = v_catatan,
          diubah_oleh = v_user_id,
          updated_at = now()
        where id = v_existing_kehadiran.id;
      end if;
    end if;
    v_updated_rows := v_updated_rows + 1;
  end loop;

  -- 7. Return summary object
  return jsonb_build_object(
    'id', v_presensi.id,
    'kelas_id', v_presensi.kelas_id,
    'tanggal', v_presensi.tanggal,
    'status', v_presensi.status,
    'versi', v_presensi.versi,
    'selesai_pada', v_presensi.selesai_pada,
    'dicatat_oleh', v_presensi.dicatat_oleh,
    'total_baris', v_updated_rows
  );
end;
$$;

-- Overload for single-object payload invocation
create or replace function public.simpan_presensi(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_kelas_id bigint;
  v_tanggal date;
  v_versi int;
  v_baris jsonb;
  v_selesaikan boolean;
  v_alasan text;
begin
  v_kelas_id := coalesce((p_payload->>'kelas_id')::bigint, (p_payload->>'kelasId')::bigint);
  v_tanggal := coalesce((p_payload->>'tanggal')::date);
  v_versi := coalesce((p_payload->>'versi')::int, 1);
  v_baris := coalesce(p_payload->'baris', '[]'::jsonb);
  v_selesaikan := coalesce((p_payload->>'selesaikan')::boolean, false);
  v_alasan := p_payload->>'alasan';

  return public.simpan_presensi(
    v_kelas_id,
    v_tanggal,
    v_versi,
    v_baris,
    v_selesaikan,
    v_alasan
  );
end;
$$;

-- Storage
insert into storage.buckets (id, name, public) values ('images', 'images', true)
on conflict (id) do nothing;
create policy "Admins can upload images" on storage.objects for insert to authenticated with check (bucket_id = 'images' and public.is_admin());
create policy "Admins can update images" on storage.objects for update to authenticated using (bucket_id = 'images' and public.is_admin());
create policy "Admins can delete images" on storage.objects for delete to authenticated using (bucket_id = 'images' and public.is_admin());
create policy "Anyone can read images" on storage.objects for select using (bucket_id = 'images');
