-- Enable necessary extensions
create extension if not exists "uuid-ossp";

-- Table: users (Public profile linked to auth.users)
create table if not exists public.users (
  id uuid references auth.users on delete cascade primary key,
  nama text not null,
  email text not null unique,
  peran text not null default 'admin' check (peran in ('super-admin', 'admin')),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Table: guru
create table if not exists public.guru (
  id bigint generated by default as identity primary key,
  nama text not null,
  kategori text default 'pendidik' check (kategori in ('pendidik', 'tenaga_kependidikan')),
  jenis_kelamin text,
  jabatan text,
  mata_pelajaran text,
  urutan smallint default 0,
  aktif boolean default true,
  image_url text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Add guru_id to users now that guru table exists
alter table public.users add column guru_id bigint references public.guru(id) on delete restrict unique;

-- Table: berita
create table if not exists public.berita (
  id bigint generated by default as identity primary key,
  judul text not null,
  slug text not null unique,
  ringkasan text,
  isi text not null,
  status text default 'draft' check (status in ('draft', 'terbit')),
  diterbitkan_pada timestamptz,
  penulis_id uuid references public.users(id) on delete set null,
  image_url text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Table: struktur_organisasi
create table if not exists public.struktur_organisasi (
  id bigint generated by default as identity primary key,
  label text not null,
  guru_id bigint references public.guru(id) on delete set null,
  atasan_id bigint references public.struktur_organisasi(id) on delete cascade,
  tipe text default 'orang' check (tipe in ('orang', 'kelompok', 'penasihat')),
  nama_luar text,
  baris smallint default 1,
  urutan smallint default 0,
  image_url text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Table: ekstrakurikuler
create table if not exists public.ekstrakurikuler (
  id bigint generated by default as identity primary key,
  nama text not null,
  slug text not null unique,
  deskripsi text,
  pembina text,
  jadwal text,
  urutan smallint default 0,
  image_url text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Table: album
create table if not exists public.album (
  id bigint generated by default as identity primary key,
  judul text not null,
  slug text not null unique,
  deskripsi text,
  urutan smallint default 0,
  image_url text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Table: konten_halaman
create table if not exists public.konten_halaman (
  id bigint generated by default as identity primary key,
  kunci text not null unique,
  judul text not null,
  isi text,
  terbit boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Table: pengaturan_situs
create table if not exists public.pengaturan_situs (
  id bigint generated by default as identity primary key,
  nama_sekolah text default 'SMA Ahlul Irfan Bangsalsari',
  nama_yayasan text,
  semboyan text,
  alamat text,
  telepon text,
  whatsapp text,
  email text,
  peta_lat numeric(10, 7),
  peta_lng numeric(10, 7),
  npsn text,
  akreditasi text,
  instagram text,
  facebook text,
  youtube text,
  fakta_terverifikasi boolean default false,
  logo_url text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Phase 2 Tables (Absensi)
create table if not exists public.tahun_ajaran (
  id bigint generated by default as identity primary key,
  nama varchar(20) not null,
  semester varchar(10) not null,
  mulai_pada date not null,
  selesai_pada date not null,
  aktif boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (nama, semester)
);

create table if not exists public.kelas (
  id bigint generated by default as identity primary key,
  tahun_ajaran_id bigint not null references public.tahun_ajaran(id) on delete restrict,
  nama varchar(50) not null,
  tingkat smallint not null,
  wali_kelas_id bigint references public.guru(id) on delete restrict,
  aktif boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (tahun_ajaran_id, nama)
);

create table if not exists public.siswa (
  id bigint generated by default as identity primary key,
  kode_siswa varchar(30) not null unique,
  nama varchar(150) not null,
  jenis_kelamin varchar(1),
  aktif boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.anggota_kelas (
  id bigint generated by default as identity primary key,
  kelas_id bigint not null references public.kelas(id) on delete restrict,
  siswa_id bigint not null references public.siswa(id) on delete restrict,
  mulai_pada date not null,
  selesai_pada date,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.presensi (
  id bigint generated by default as identity primary key,
  kelas_id bigint not null references public.kelas(id) on delete restrict,
  tanggal date not null,
  status varchar(10) default 'draf',
  dicatat_oleh uuid not null references public.users(id) on delete restrict,
  versi int default 1,
  selesai_pada timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (kelas_id, tanggal)
);

create table if not exists public.kehadiran_siswa (
  id bigint generated by default as identity primary key,
  presensi_id bigint not null references public.presensi(id) on delete cascade,
  siswa_id bigint not null references public.siswa(id) on delete restrict,
  status varchar(20) default 'belum_diisi',
  catatan varchar(255),
  diubah_oleh uuid not null references public.users(id) on delete restrict,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (presensi_id, siswa_id)
);

create table if not exists public.riwayat_presensi (
  id bigint generated by default as identity primary key,
  presensi_id bigint not null references public.presensi(id) on delete restrict,
  siswa_id bigint references public.siswa(id) on delete restrict,
  user_id uuid not null references public.users(id) on delete restrict,
  aksi varchar(20) not null,
  status_sebelum varchar(20),
  status_sesudah varchar(20),
  catatan_sebelum varchar(255),
  catatan_sesudah varchar(255),
  alasan varchar(255),
  created_at timestamptz default now()
);

-- Trigger for auth.users to auto-create public.users is NOT added here because we will manage users via API securely.

-- Row Level Security (RLS) setup
alter table public.users enable row level security;
alter table public.guru enable row level security;
alter table public.berita enable row level security;
alter table public.struktur_organisasi enable row level security;
alter table public.ekstrakurikuler enable row level security;
alter table public.album enable row level security;
alter table public.konten_halaman enable row level security;
alter table public.pengaturan_situs enable row level security;
alter table public.tahun_ajaran enable row level security;
alter table public.kelas enable row level security;
alter table public.siswa enable row level security;
alter table public.anggota_kelas enable row level security;
alter table public.presensi enable row level security;
alter table public.kehadiran_siswa enable row level security;
alter table public.riwayat_presensi enable row level security;

-- Policies for public reading
create policy "Allow public read access to active guru" on public.guru for select using (aktif = true);
create policy "Allow public read access to published berita" on public.berita for select using (status = 'terbit');
create policy "Allow public read access to struktur_organisasi" on public.struktur_organisasi for select using (true);
create policy "Allow public read access to ekstrakurikuler" on public.ekstrakurikuler for select using (true);
create policy "Allow public read access to album" on public.album for select using (true);
create policy "Allow public read access to published konten_halaman" on public.konten_halaman for select using (terbit = true);
create policy "Allow public read access to pengaturan_situs" on public.pengaturan_situs for select using (true);

-- Functions to check if user is admin
create or replace function public.is_admin() returns boolean as $$
  select exists (
    select 1 from public.users where id = auth.uid() and peran in ('admin', 'super-admin')
  );
$$ language sql security definer;

-- Policies for admins to read/write all
create policy "Admins can do everything on guru" on public.guru to authenticated using (public.is_admin());
create policy "Admins can do everything on berita" on public.berita to authenticated using (public.is_admin());
create policy "Admins can do everything on struktur_organisasi" on public.struktur_organisasi to authenticated using (public.is_admin());
create policy "Admins can do everything on ekstrakurikuler" on public.ekstrakurikuler to authenticated using (public.is_admin());
create policy "Admins can do everything on album" on public.album to authenticated using (public.is_admin());
create policy "Admins can do everything on konten_halaman" on public.konten_halaman to authenticated using (public.is_admin());
create policy "Admins can do everything on pengaturan_situs" on public.pengaturan_situs to authenticated using (public.is_admin());
create policy "Admins can do everything on users" on public.users to authenticated using (public.is_admin());
create policy "Admins can do everything on tahun_ajaran" on public.tahun_ajaran to authenticated using (public.is_admin());
create policy "Admins can do everything on kelas" on public.kelas to authenticated using (public.is_admin());
create policy "Admins can do everything on siswa" on public.siswa to authenticated using (public.is_admin());
create policy "Admins can do everything on anggota_kelas" on public.anggota_kelas to authenticated using (public.is_admin());
create policy "Admins can do everything on presensi" on public.presensi to authenticated using (public.is_admin());
create policy "Admins can do everything on kehadiran_siswa" on public.kehadiran_siswa to authenticated using (public.is_admin());
create policy "Admins can do everything on riwayat_presensi" on public.riwayat_presensi to authenticated using (public.is_admin());

-- Storage
insert into storage.buckets (id, name, public) values ('images', 'images', true);
create policy "Admins can upload images" on storage.objects for insert to authenticated with check (bucket_id = 'images' and public.is_admin());
create policy "Admins can update images" on storage.objects for update to authenticated using (bucket_id = 'images' and public.is_admin());
create policy "Admins can delete images" on storage.objects for delete to authenticated using (bucket_id = 'images' and public.is_admin());
create policy "Anyone can read images" on storage.objects for select using (bucket_id = 'images');
